services:
  postgres:
    image: postgres:16
    container_name: service-booking-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"

    networks:
      - service-booking-network

  api:
    build:
      context: ./backend/ServiceBooking.Api
      dockerfile: Dockerfile

    container_name: service-booking-api
    restart: unless-stopped

    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      Swagger__Enabled: "true"

      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=${POSTGRES_DB};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD}"

      Jwt__Key: ${JWT_KEY}

    expose:
      - "8080"

    depends_on:
      - postgres

    networks:
      - service-booking-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile

      args:
        NEXT_PUBLIC_API_URL: /api

    container_name: service-booking-frontend
    restart: unless-stopped

    expose:
      - "3000"

    depends_on:
      - api

    networks:
      - service-booking-network

  nginx:
    image: nginx:alpine
    container_name: service-booking-nginx
    restart: unless-stopped

    ports:
      - "80:80"

    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro

    depends_on:
      - frontend
      - api

    networks:
      - service-booking-network

volumes:
  postgres_data:

networks:
  service-booking-network:
    driver: bridge
